const OrderActionTypes = {

    SEARCH_ORDER_BY_ID_START : "SEARCH_ORDER_BY_ID_START",
    SEARCH_ORDER_BY_ID_SUCCESS : "SEARCH_ORDER_BY_ID_SUCCESS",
    SEARCH_ORDER_BY_ID_FAILURE : "SEARCH_ORDER_BY_ID_FAILURE",

    CREATE_ORDER_START : "CREATE_ORDER_START",
    CREATE_ORDER_SUCCESS : "CREATE_ORDER_SUCCESS",
    CREATE_ORDER_FAILURE : "CREATE_ORDER_FAILURE"

}

export default OrderActionTypes;